version: 2.1

workflows:
  ci:
    jobs:
      - backend-test

jobs:
  build-and-test:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true
    resource_class: medium
    working_directory: ~/flask_gerlessver
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "requirements.txt" }}-{{ checksum "package.json" }}
            
      - run:
          name: Build 
          command: |
            ARG_USER_UID=$(id -u) ARG_USER_GID=$(id -g) docker compose config
            ARG_USER_UID=$(id -u) ARG_USER_GID=$(id -g) docker compose build
      - run:
          name: Up
          command: docker compose up -d
      - run:
          name: Dependencies
          command: |
            docker compose exec app pip install -r requirements.txt
      - run:
          name:  Dependencies
          command: |
            docker compose exec app npm install
      - save_cache:
          paths:
            - ./venv
            - ./node_modules
          key: deps-{{ checksum "requirements.txt" }}-{{ checksum "package.json" }}
     