version: 2.1

workflows:
  ci:
    jobs:
      - back

jobs:
  back:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true
    resource_class: medium
    working_directory: ~/flask_gerlessver
    steps:
      - checkout
      - run:
          name: List files
          command: ls -alh ~/flask_gerlessver
      - restore_cache:
          name: Restore Cache
          key: '{{ checksum "requirements.txt" }}'
      - run:
          name: Build
          command: |
            docker compose config
            docker compose build
      - run:
          name: Up
          command: |
            docker compose up -d
            docker compose exec app pip install -r requirements.txt
            docker compose exec app npm install

      - save_cache:
          name: Save Cache
          key: '{{ checksum "requirements.txt" }}'
          paths:
            - ./node_modules
            - ./vendor
